/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Usuario;

/**
 *
 * @author USER
 */
public class Programa extends javax.swing.JFrame {
    Usuario usuario;
    
    
    public Programa() {
        initComponents();
    }
    
    public Programa (Usuario usuario){
        initComponents();
        setLocationRelativeTo(null);
        this.usuario = usuario;
        
        
        
        etiquetaNombre.setText(usuario.getNombre());
        etiquetaRol.setText(usuario.getNombreRol());
        
        if(usuario.getIdTipo_usuario() == 1){
            
        }
        else if(usuario.getIdTipo_usuario() == 2){
            menuContacto.setVisible(false);
            subMenuModificarItem.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaRol = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInventario = new javax.swing.JMenu();
        subMenuAgregarItem = new javax.swing.JMenuItem();
        subMenuModificarItem = new javax.swing.JMenuItem();
        subMenuConsultarItem = new javax.swing.JMenuItem();
        menuContacto = new javax.swing.JMenu();
        subMenuAgregarContacto = new javax.swing.JMenuItem();
        subMenuModificarContacto = new javax.swing.JMenuItem();
        subMenuConsultarContacto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("¡Bienvenido!");

        etiquetaNombre.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N

        etiquetaRol.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N

        menuInventario.setText("Inventario");

        subMenuAgregarItem.setText("Agregar ítem");
        menuInventario.add(subMenuAgregarItem);

        subMenuModificarItem.setText("Modificar ítem");
        subMenuModificarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuModificarItemActionPerformed(evt);
            }
        });
        menuInventario.add(subMenuModificarItem);

        subMenuConsultarItem.setText("Catálogo de ítems");
        menuInventario.add(subMenuConsultarItem);

        jMenuBar1.add(menuInventario);

        menuContacto.setText("Contactos");

        subMenuAgregarContacto.setText("Agregar contacto");
        menuContacto.add(subMenuAgregarContacto);

        subMenuModificarContacto.setText("Modificar contacto");
        menuContacto.add(subMenuModificarContacto);

        subMenuConsultarContacto.setText("Catálogo de contactos");
        menuContacto.add(subMenuConsultarContacto);

        jMenuBar1.add(menuContacto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaRol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(etiquetaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaRol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuModificarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuModificarItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuModificarItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuContacto;
    private javax.swing.JMenu menuInventario;
    private javax.swing.JMenuItem subMenuAgregarContacto;
    private javax.swing.JMenuItem subMenuAgregarItem;
    private javax.swing.JMenuItem subMenuConsultarContacto;
    private javax.swing.JMenuItem subMenuConsultarItem;
    private javax.swing.JMenuItem subMenuModificarContacto;
    private javax.swing.JMenuItem subMenuModificarItem;
    // End of variables declaration//GEN-END:variables
}
